name = "geompack"
version = "1.0.0"
license = "GPL-3.0"
author = "Jason Christopherson"
maintainer = "Jason Christopherson"
copyright = "Copyright 2023, Jason Christopherson"
description = "A modernization of the GEOMPACK library for computing Delaunay triangulations."
homepage = "https://github.com/jchristopherson/geompack"

[fortran]
implicit-typing = true
implicit-external = true
source-form = "default"

[library]
source-dir = "src"

[install]
library = true

[build]
auto-executables = false
auto-examples = false
auto-tests = false

[dev-dependencies]
fortran_test_helper = { git = "https://github.com/jchristopherson/fortran_test_helper" }

[[test]]
name = "geompack_test"
source-dir = "test"
main = "geompack_test.f90"